/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuySuccessRouteImport } from './routes/buy.success'
import { Route as BusinessLandingRouteImport } from './routes/business.landing'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySuccessRoute = BuySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BuyRoute,
} as any)
const BusinessLandingRoute = BusinessLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => BusinessRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteWithChildren
  '/buy': typeof BuyRouteWithChildren
  '/redeem': typeof RedeemRoute
  '/business/landing': typeof BusinessLandingRoute
  '/buy/success': typeof BuySuccessRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteWithChildren
  '/buy': typeof BuyRouteWithChildren
  '/redeem': typeof RedeemRoute
  '/business/landing': typeof BusinessLandingRoute
  '/buy/success': typeof BuySuccessRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteWithChildren
  '/buy': typeof BuyRouteWithChildren
  '/redeem': typeof RedeemRoute
  '/business/landing': typeof BusinessLandingRoute
  '/buy/success': typeof BuySuccessRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/buy'
    | '/redeem'
    | '/business/landing'
    | '/buy/success'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business'
    | '/buy'
    | '/redeem'
    | '/business/landing'
    | '/buy/success'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/buy'
    | '/redeem'
    | '/business/landing'
    | '/buy/success'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  BuyRoute: typeof BuyRouteWithChildren
  RedeemRoute: typeof RedeemRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/success': {
      id: '/buy/success'
      path: '/success'
      fullPath: '/buy/success'
      preLoaderRoute: typeof BuySuccessRouteImport
      parentRoute: typeof BuyRoute
    }
    '/business/landing': {
      id: '/business/landing'
      path: '/landing'
      fullPath: '/business/landing'
      preLoaderRoute: typeof BusinessLandingRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BusinessRouteChildren {
  BusinessLandingRoute: typeof BusinessLandingRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessLandingRoute: BusinessLandingRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface BuyRouteChildren {
  BuySuccessRoute: typeof BuySuccessRoute
}

const BuyRouteChildren: BuyRouteChildren = {
  BuySuccessRoute: BuySuccessRoute,
}

const BuyRouteWithChildren = BuyRoute._addFileChildren(BuyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRouteWithChildren,
  BuyRoute: BuyRouteWithChildren,
  RedeemRoute: RedeemRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
