/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewportRouteImport } from './routes/viewport'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GlobalAccessRouteImport } from './routes/global-access'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayLocalRouteImport } from './routes/pay.local'
import { Route as PayCryptoRouteImport } from './routes/pay.crypto'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BuySuccessRouteImport } from './routes/buy.success'
import { Route as BuyReturnRouteImport } from './routes/buy.return'
import { Route as BusinessLandingRouteImport } from './routes/business.landing'
import { Route as AdminCoverageRouteImport } from './routes/admin.coverage'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as GiftTrackOrderIdRouteImport } from './routes/gift.track.$orderId'
import { Route as ApiPublicSubmitLeadRouteImport } from './routes/api/public/submit-lead'
import { Route as ApiPublicSendEmailRouteImport } from './routes/api/public/send-email'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const ViewportRoute = ViewportRouteImport.update({
  id: '/viewport',
  path: '/viewport',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalAccessRoute = GlobalAccessRouteImport.update({
  id: '/global-access',
  path: '/global-access',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayLocalRoute = PayLocalRouteImport.update({
  id: '/pay/local',
  path: '/pay/local',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCryptoRoute = PayCryptoRouteImport.update({
  id: '/pay/crypto',
  path: '/pay/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySuccessRoute = BuySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BuyRoute,
} as any)
const BuyReturnRoute = BuyReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => BuyRoute,
} as any)
const BusinessLandingRoute = BusinessLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => BusinessRoute,
} as any)
const AdminCoverageRoute = AdminCoverageRouteImport.update({
  id: '/admin/coverage',
  path: '/admin/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftTrackOrderIdRoute = GiftTrackOrderIdRouteImport.update({
  id: '/gift/track/$orderId',
  path: '/gift/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmitLeadRoute = ApiPublicSubmitLeadRouteImport.update({
  id: '/api/public/submit-lead',
  path: '/api/public/submit-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendEmailRoute = ApiPublicSendEmailRouteImport.update({
  id: '/api/public/send-email',
  path: '/api/public/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/business': typeof BusinessRouteWithChildren
  '/buy': typeof BuyRouteWithChildren
  '/claim': typeof ClaimRoute
  '/cookies': typeof CookiesRoute
  '/global-access': typeof GlobalAccessRoute
  '/how-it-works': typeof HowItWorksRoute
  '/manifesto': typeof ManifestoRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/redeem': typeof RedeemRoute
  '/refunds': typeof RefundsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/viewport': typeof ViewportRoute
  '/admin/coverage': typeof AdminCoverageRoute
  '/business/landing': typeof BusinessLandingRoute
  '/buy/return': typeof BuyReturnRoute
  '/buy/success': typeof BuySuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/pay/crypto': typeof PayCryptoRoute
  '/pay/local': typeof PayLocalRoute
  '/api/public/send-email': typeof ApiPublicSendEmailRoute
  '/api/public/submit-lead': typeof ApiPublicSubmitLeadRoute
  '/gift/track/$orderId': typeof GiftTrackOrderIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/business': typeof BusinessRouteWithChildren
  '/buy': typeof BuyRouteWithChildren
  '/claim': typeof ClaimRoute
  '/cookies': typeof CookiesRoute
  '/global-access': typeof GlobalAccessRoute
  '/how-it-works': typeof HowItWorksRoute
  '/manifesto': typeof ManifestoRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/redeem': typeof RedeemRoute
  '/refunds': typeof RefundsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/viewport': typeof ViewportRoute
  '/admin/coverage': typeof AdminCoverageRoute
  '/business/landing': typeof BusinessLandingRoute
  '/buy/return': typeof BuyReturnRoute
  '/buy/success': typeof BuySuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/pay/crypto': typeof PayCryptoRoute
  '/pay/local': typeof PayLocalRoute
  '/api/public/send-email': typeof ApiPublicSendEmailRoute
  '/api/public/submit-lead': typeof ApiPublicSubmitLeadRoute
  '/gift/track/$orderId': typeof GiftTrackOrderIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/business': typeof BusinessRouteWithChildren
  '/buy': typeof BuyRouteWithChildren
  '/claim': typeof ClaimRoute
  '/cookies': typeof CookiesRoute
  '/global-access': typeof GlobalAccessRoute
  '/how-it-works': typeof HowItWorksRoute
  '/manifesto': typeof ManifestoRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/redeem': typeof RedeemRoute
  '/refunds': typeof RefundsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/viewport': typeof ViewportRoute
  '/admin/coverage': typeof AdminCoverageRoute
  '/business/landing': typeof BusinessLandingRoute
  '/buy/return': typeof BuyReturnRoute
  '/buy/success': typeof BuySuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/pay/crypto': typeof PayCryptoRoute
  '/pay/local': typeof PayLocalRoute
  '/api/public/send-email': typeof ApiPublicSendEmailRoute
  '/api/public/submit-lead': typeof ApiPublicSubmitLeadRoute
  '/gift/track/$orderId': typeof GiftTrackOrderIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/business'
    | '/buy'
    | '/claim'
    | '/cookies'
    | '/global-access'
    | '/how-it-works'
    | '/manifesto'
    | '/orders'
    | '/pricing'
    | '/privacy'
    | '/redeem'
    | '/refunds'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/unsubscribe'
    | '/viewport'
    | '/admin/coverage'
    | '/business/landing'
    | '/buy/return'
    | '/buy/success'
    | '/email/unsubscribe'
    | '/pay/crypto'
    | '/pay/local'
    | '/api/public/send-email'
    | '/api/public/submit-lead'
    | '/gift/track/$orderId'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/business'
    | '/buy'
    | '/claim'
    | '/cookies'
    | '/global-access'
    | '/how-it-works'
    | '/manifesto'
    | '/orders'
    | '/pricing'
    | '/privacy'
    | '/redeem'
    | '/refunds'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/unsubscribe'
    | '/viewport'
    | '/admin/coverage'
    | '/business/landing'
    | '/buy/return'
    | '/buy/success'
    | '/email/unsubscribe'
    | '/pay/crypto'
    | '/pay/local'
    | '/api/public/send-email'
    | '/api/public/submit-lead'
    | '/gift/track/$orderId'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/business'
    | '/buy'
    | '/claim'
    | '/cookies'
    | '/global-access'
    | '/how-it-works'
    | '/manifesto'
    | '/orders'
    | '/pricing'
    | '/privacy'
    | '/redeem'
    | '/refunds'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/unsubscribe'
    | '/viewport'
    | '/admin/coverage'
    | '/business/landing'
    | '/buy/return'
    | '/buy/success'
    | '/email/unsubscribe'
    | '/pay/crypto'
    | '/pay/local'
    | '/api/public/send-email'
    | '/api/public/submit-lead'
    | '/gift/track/$orderId'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  BuyRoute: typeof BuyRouteWithChildren
  ClaimRoute: typeof ClaimRoute
  CookiesRoute: typeof CookiesRoute
  GlobalAccessRoute: typeof GlobalAccessRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ManifestoRoute: typeof ManifestoRoute
  OrdersRoute: typeof OrdersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RedeemRoute: typeof RedeemRoute
  RefundsRoute: typeof RefundsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ViewportRoute: typeof ViewportRoute
  AdminCoverageRoute: typeof AdminCoverageRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PayCryptoRoute: typeof PayCryptoRoute
  PayLocalRoute: typeof PayLocalRoute
  ApiPublicSendEmailRoute: typeof ApiPublicSendEmailRoute
  ApiPublicSubmitLeadRoute: typeof ApiPublicSubmitLeadRoute
  GiftTrackOrderIdRoute: typeof GiftTrackOrderIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewport': {
      id: '/viewport'
      path: '/viewport'
      fullPath: '/viewport'
      preLoaderRoute: typeof ViewportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-access': {
      id: '/global-access'
      path: '/global-access'
      fullPath: '/global-access'
      preLoaderRoute: typeof GlobalAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/local': {
      id: '/pay/local'
      path: '/pay/local'
      fullPath: '/pay/local'
      preLoaderRoute: typeof PayLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/crypto': {
      id: '/pay/crypto'
      path: '/pay/crypto'
      fullPath: '/pay/crypto'
      preLoaderRoute: typeof PayCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/success': {
      id: '/buy/success'
      path: '/success'
      fullPath: '/buy/success'
      preLoaderRoute: typeof BuySuccessRouteImport
      parentRoute: typeof BuyRoute
    }
    '/buy/return': {
      id: '/buy/return'
      path: '/return'
      fullPath: '/buy/return'
      preLoaderRoute: typeof BuyReturnRouteImport
      parentRoute: typeof BuyRoute
    }
    '/business/landing': {
      id: '/business/landing'
      path: '/landing'
      fullPath: '/business/landing'
      preLoaderRoute: typeof BusinessLandingRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/admin/coverage': {
      id: '/admin/coverage'
      path: '/admin/coverage'
      fullPath: '/admin/coverage'
      preLoaderRoute: typeof AdminCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/track/$orderId': {
      id: '/gift/track/$orderId'
      path: '/gift/track/$orderId'
      fullPath: '/gift/track/$orderId'
      preLoaderRoute: typeof GiftTrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-lead': {
      id: '/api/public/submit-lead'
      path: '/api/public/submit-lead'
      fullPath: '/api/public/submit-lead'
      preLoaderRoute: typeof ApiPublicSubmitLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-email': {
      id: '/api/public/send-email'
      path: '/api/public/send-email'
      fullPath: '/api/public/send-email'
      preLoaderRoute: typeof ApiPublicSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BusinessRouteChildren {
  BusinessLandingRoute: typeof BusinessLandingRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessLandingRoute: BusinessLandingRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface BuyRouteChildren {
  BuyReturnRoute: typeof BuyReturnRoute
  BuySuccessRoute: typeof BuySuccessRoute
}

const BuyRouteChildren: BuyRouteChildren = {
  BuyReturnRoute: BuyReturnRoute,
  BuySuccessRoute: BuySuccessRoute,
}

const BuyRouteWithChildren = BuyRoute._addFileChildren(BuyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BusinessRoute: BusinessRouteWithChildren,
  BuyRoute: BuyRouteWithChildren,
  ClaimRoute: ClaimRoute,
  CookiesRoute: CookiesRoute,
  GlobalAccessRoute: GlobalAccessRoute,
  HowItWorksRoute: HowItWorksRoute,
  ManifestoRoute: ManifestoRoute,
  OrdersRoute: OrdersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RedeemRoute: RedeemRoute,
  RefundsRoute: RefundsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ViewportRoute: ViewportRoute,
  AdminCoverageRoute: AdminCoverageRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PayCryptoRoute: PayCryptoRoute,
  PayLocalRoute: PayLocalRoute,
  ApiPublicSendEmailRoute: ApiPublicSendEmailRoute,
  ApiPublicSubmitLeadRoute: ApiPublicSubmitLeadRoute,
  GiftTrackOrderIdRoute: GiftTrackOrderIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
